name: Simple compile test 

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: g++ -o adrift ./src/main.cpp -static

      - name: Test makefile
        run: make adrift
