name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Ensure compilation under g++
      run: g++ -o adrift ./src/main.cpp
    - name: Test make
      run: make adrift
